version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 10
    reviewers:
      - "jon-the-dev"
    assignees:
      - "jon-the-dev"
    labels:
      - "dependencies"
      - "npm"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 10
    reviewers:
      - "jon-the-dev"
    assignees:
      - "jon-the-dev"
    labels:
      - "dependencies"
      - "npm"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 10
    reviewers:
      - "jon-the-dev"
    assignees:
      - "jon-the-dev"
    labels:
      - "dependencies"
      - "python"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "jon-the-dev"
    assignees:
      - "jon-the-dev"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
