#!/usr/bin/env python3
"""Render the command reference sections of the docs from the live Click tree.

Each generated region is delimited by markers so hand-written prose around it
survives regeneration:

    <!-- BEGIN GENERATED: commands -->
    ...generated content...
    <!-- END GENERATED: commands -->

Usage:
    python scripts/gen_docs.py           # rewrite generated regions in place
    python scripts/gen_docs.py --check   # exit 1 if any region is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import List, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

from cli_introspect import PROG, Node, build_root  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"

BEGIN = "<!-- BEGIN GENERATED: {name} -->"
END = "<!-- END GENERATED: {name} -->"
WARNING = "<!-- Generated by scripts/gen_docs.py -- do not edit between these markers. -->"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _usage(node: Node) -> str:
    parts = [PROG, node.path]
    for arg in node.arguments:
        name = arg.opts[0]
        parts.append(name if arg.required else f"[{name}]")
    if node.is_group:
        parts.append("COMMAND")
    if node.options:
        parts.append("[OPTIONS]")
    return " ".join(p for p in parts if p)


def _value(param) -> str:
    if param.choices:
        return "`" + "` \\| `".join(param.choices) + "`"
    if param.metavar:
        return f"`{param.metavar}`"
    return "flag"


def _option_table(node: Node) -> List[str]:
    if not node.options:
        return []
    rows = ["| Option | Value | Description |", "|---|---|---|"]
    for param in node.options:
        flags = ", ".join(f"`{o}`" for o in param.opts)
        desc = _cell(param.help or "")
        if param.multiple:
            desc = f"{desc} (repeatable)".strip()
        if param.required:
            desc = f"**Required.** {desc}".strip()
        elif param.default and "default:" not in desc.lower():
            desc = f"{desc} (default: `{param.default}`)".strip()
        rows.append(f"| {flags} | {_value(param)} | {desc} |")
    rows.append("")
    return rows


def _argument_table(node: Node) -> List[str]:
    """Render positional arguments, but only when they carry help text.

    Click arguments have no ``help``, so without it the table is an empty
    column. The usage line already shows the names and, via brackets, which
    are optional.
    """
    if not node.arguments or not any(p.help for p in node.arguments):
        return []
    rows = ["| Argument | Required | Description |", "|---|---|---|"]
    for param in node.arguments:
        req = "Yes" if param.required else "No"
        rows.append(f"| `{param.opts[0]}` | {req} | {_cell(param.help or '')} |")
    rows.append("")
    return rows


def render_node(node: Node, depth: int) -> str:
    """Render one command (and its subcommands) as a markdown section."""
    heading = "#" * depth
    label = node.path or node.name
    out = [f"{heading} `{label}`", ""]
    if node.summary:
        out += [node.summary, ""]
    out += ["```bash", _usage(node), "```", ""]
    out += _argument_table(node)
    out += _option_table(node)
    for child in node.children.values():
        out.append(render_node(child, depth + 1))
    return "\n".join(out)


def render_group_body(name: str) -> str:
    """The reference block for one command page (subcommands only, no group heading)."""
    group = build_root().children[name]
    if not group.children:
        # Standalone command such as ``configure`` or ``info``.
        body = ["```bash", _usage(group), "```", ""]
        body += _argument_table(group)
        body += _option_table(group)
        return "\n".join(body).rstrip() + "\n"
    blocks = [render_node(child, 3) for child in group.children.values()]
    return "\n".join(blocks).rstrip() + "\n"


def render_services_table(link_prefix: str) -> str:
    """Markdown table of every top-level command, linking to its page."""
    root = build_root()
    rows = ["| Command | Description | Subcommands |", "|---------|-------------|-------------|"]
    for name, node in root.children.items():
        if node.children:
            subs = ", ".join(f"`{s}`" for s in sorted(node.children))
        else:
            subs = "_(none)_"
        rows.append(f"| [**{name}**]({link_prefix}{name}.md) | {_cell(node.summary)} | {subs} |")
    return "\n".join(rows) + "\n"


def render_global_options() -> str:
    rows = ["| Option | Value | Description |", "|---|---|---|"]
    for param in build_root().options:
        flags = ", ".join(f"`{o}`" for o in param.opts)
        rows.append(f"| {flags} | {_value(param)} | {_cell(param.help or '')} |")
    return "\n".join(rows) + "\n"


def render_full_reference() -> str:
    """Every command in one flat listing for reference/cli.md."""
    root = build_root()
    out: List[str] = []
    for name, node in root.children.items():
        out.append(render_node(node, 2))
    return "\n".join(out).rstrip() + "\n"


def render_command_matrix() -> str:
    """Flat table of every runnable command, for quick scanning."""
    rows = ["| Command | Description |", "|---|---|"]
    for leaf in build_root().leaves():
        rows.append(f"| `{PROG} {leaf.path}` | {_cell(leaf.summary)} |")
    return "\n".join(rows) + "\n"


def replace_region(path: Path, name: str, content: str) -> bool:
    """Swap the contents of a marker region. Returns True if the file changed."""
    text = path.read_text()
    begin, end = BEGIN.format(name=name), END.format(name=name)
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"error: {path.relative_to(REPO_ROOT)} has no '{name}' generated region")
    new = pattern.sub(lambda _: f"{begin}\n{WARNING}\n\n{content.rstrip()}\n\n{end}", text)
    if new == text:
        return False
    path.write_text(new)
    return True


def targets() -> List[Tuple[Path, str, str]]:
    items: List[Tuple[Path, str, str]] = []
    for name in build_root().children:
        items.append((DOCS / "commands" / f"{name}.md", "commands", render_group_body(name)))
    items.append((DOCS / "index.md", "services-table", render_services_table("commands/")))
    items.append((DOCS / "commands" / "index.md", "services-table", render_services_table("")))
    items.append((DOCS / "commands" / "index.md", "command-matrix", render_command_matrix()))
    items.append((DOCS / "reference" / "cli.md", "global-options", render_global_options()))
    items.append((DOCS / "reference" / "cli.md", "full-reference", render_full_reference()))
    return items


def main() -> int:
    check = "--check" in sys.argv
    changed: List[str] = []

    for page, region, body in targets():
        if not page.exists():
            raise SystemExit(f"error: missing page {page.relative_to(REPO_ROOT)}")
        original = page.read_text()
        if replace_region(page, region, body):
            changed.append(f"{page.relative_to(REPO_ROOT)} [{region}]")
            if check:
                page.write_text(original)

    if check:
        if changed:
            print("Generated docs are stale. Run 'make docs-gen':")
            for item in changed:
                print(f"  {item}")
            return 1
        print("Generated command reference is up to date.")
        return 0

    for item in changed:
        print(f"updated {item}")
    if not changed:
        print("No changes; generated command reference already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
